### ISSUE TITLE
part1: unneeded type-assert

### ISSUE THREAD

**Issue by sbinet** [prl900/earth_data_server#1]
there's an unneeded type-assertion in:

https://github.com/prl900/earth_data_server/blob/9e442b6382f507b338d2ea96e86dfceef81d4afa/part1/get_region_tiles.go#L56

`image/draw.Draw` and `golang.org/x/image/draw.Draw` both take directly an `image.Image` as `src`:

- https://godoc.org/image/draw#Draw
- https://godoc.org/golang.org/x/image/draw#Draw

so there's no need to type-assert `tile` into an `*image.RGBA`.
`draw.Draw` will do it internally to discover fast paths.
type-asserting twice is just redundant :)

it should shave off a few perf units.

**Comment by prl900** [comment]
Good catch @sbinet and thanks for pointing that out!
This has been fixed on commit https://github.com/prl900/earth_data_server/commit/6f651c87a9c3649636d7053210a715fc22e8a883
